name: chroma_browser
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  build_runner: ^2.10.4
  flutter:
    sdk: flutter
  freezed: ^3.2.3
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
